baseURL = "/"
languageCode = "en-us"
title = "MOND←TECH MAGAZINE"

buildFuture = true
buildDrafts = false
paginate = 12

DefaultContentLanguage = "en"
pluralizelisttitles = "false"

refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "/"

timeout = 60000

rssLimit = 3

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'pygments'
    # style = 'colorful'
    # style = 'emacs'
    # style = 'monokailight'
    # style = 'rainbow_dash'
    tabWidth = 4


enableInlineShortcodes = true

[permalinks]
	posts = '/:year/:month/:slugorfilename/'
  categories = '/:slug/'

[params]
	author = "Mond"
  newsletter = "https://d69baa34.sibforms.com/serve/MUIEAJWIw9w82Dl4ua6FQArPaI-3Qb-zVTwPNabHQgFH51MiGF69Smy9LOC_HPoUmBj0emaXsXT87gcQXDPvtu-AZsJCHWhkkv21CdrcQu4GdnYAhZ-MrIPhwGDecagLzYxqfvkaqXg2ODcbJU4ByoDmzJK3ZTczDo2jcWtfn-En0MGKLVkgxx9TgdHqYoPabMJCMF-agLEclEwv"
  mail = "mailto:example@example.com"
  sanitizedMail = "example [at] example [dot] com"
  description = "This is a website, which means it sometimes goes offline"
  github = "https://github.com/HereComesTheMoon"

[menu]
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "archives"
  name = "Archive"
  url = "/archives/"
  weight = 2

defaultContentLanguage = 'en'
[languages]
	[languages.en]
    languageName = 'English'
	  weight = 1

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
  translator = "translators"
  lang = "languages"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'lang'
  weight = 80
  

